const express = require('express');
const router = express.Router();
const puppeteer = require('puppeteer');
const asyncHandler = require('express-async-handler');
const { protect, authorize } = require('../middleware/authMiddleware');

const axios = require('axios');

const ASSESSMENT_SERVICE_URL = process.env.ASSESSMENT_SERVICE_URL || 'http://localhost:5003/api/assessment';
const QUIZ_SERVICE_URL = process.env.QUIZ_SERVICE_URL || 'http://localhost:5002/api/quizzes';

// Get Instructor Dashboard Stats
router.get('/instructor-stats', protect, authorize('Instructor'), asyncHandler(async (req, res) => {
  const instructorId = req.user.id;
  const token = req.headers.authorization;

  // 1. Get instructor's quizzes
  const { data: quizzes } = await axios.get(`${QUIZ_SERVICE_URL}/instructor/${instructorId}`, {
    headers: { Authorization: token }
  });

  const quizIds = quizzes.map(q => q._id);

  // 2. Get aggregate stats from Assessment service
  const { data: stats } = await axios.post(`${ASSESSMENT_SERVICE_URL}/stats/instructor`,
    { quizIds },
    { headers: { Authorization: token } }
  );

  res.json({
    totalQuizzes: quizzes.length,
    activeStudents: stats.activeStudents,
    avgScore: stats.avgScore
  });
}));

// Get Student Dashboard Stats
router.get('/student-stats', protect, asyncHandler(async (req, res) => {
  const userId = req.user.id;
  const token = req.headers.authorization;

  // 1. Get all quizzes count (for comparison/context)
  const { data: allQuizzes } = await axios.get(QUIZ_SERVICE_URL, {
    headers: { Authorization: token }
  });

  // 2. Get student stats from Assessment service
  const { data: stats } = await axios.get(`${ASSESSMENT_SERVICE_URL}/stats/student/${userId}`, {
    headers: { Authorization: token }
  });

  res.json({
    availableQuizzes: allQuizzes.length,
    completedQuizzes: stats.completedCount,
    certificates: stats.certificatesCount
  });
}));

// Get Analytics for a Quiz - Instructor Only
router.get('/analytics/:quizId', protect, authorize('Instructor'), asyncHandler(async (req, res) => {
  res.json({ message: 'Analytics data for quiz ' + req.params.quizId });
}));

// Generate PDF Report - Protected
router.get('/pdf/:submissionId', protect, asyncHandler(async (req, res) => {
  const { submissionId } = req.params;

  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  const htmlContent = `
    <html>
      <body style="font-family: sans-serif; padding: 40px; color: #333;">
        <h1 style="color: #6366f1;">Quiz Submission Report</h1>
        <hr style="border: 0; border-top: 2px solid #eee; margin: 20px 0;" />
        <p><strong>Submission ID:</strong> ${submissionId}</p>
        <p><strong>Status:</strong> Completed</p>
        <p><strong>Generated at:</strong> ${new Date().toLocaleString()}</p>
        <div style="margin-top: 40px; padding: 20px; background: #f8fafc; border-radius: 8px;">
          <p>This is an enterprise-grade automated report generated by QMS.</p>
        </div>
      </body>
    </html>
  `;

  await page.setContent(htmlContent);
  const pdf = await page.pdf({ format: 'A4' });

  await browser.close();

  res.contentType("application/pdf");
  res.send(pdf);
}));

module.exports = router;
